### ISSUE TITLE
Support --trace-directory and --trace-silent parameters

### ISSUE THREAD

**Issue by rdagumampan** [rdagumampan/yuniql#101]
This enhancements allows users to define when and where to store the logs of migration.

` --trace-directory`: This parameter allows users to define the directory where the log files will be created
`--trace-silent`: This parameter disables creation of a log file but maintain logs in console output

**Comment by TaurahSP** [comment]
@rdagumampan  can i take this one?

**Comment by rdagumampan** [comment]
Please do. Thanks! Sorry for late response.

**Comment by rdagumampan** [comment]
Hi @TaurahSP I hope you had great new year. May I ask if you are still interested in this feature? :) Im preparing a roadmap for Q12021 release and I think this is a good contribution. Br, Rodel

**Comment by bobi591** [comment]
Hi @rdagumampan. 

About the "--trace-directory". 
I was thinking to make some kind of check if the directory exists when the Program.cs Dispatch is called. 
Otherwise the program can throw exceptions during command execution.
Catch the exceptions within the command trace executions is another feasible approach, but at the end of execution of the command the user will not have his/her traces saved as he may have initially expected.

Do you think it will be OK to make a method in the TraceService that will check if the directory exists and throw an exception prior command execution (aka in the Program.cs Dispatch method)?

Also do you think it is a good idea to add another check in the same method that checks the if the Trace Directory string ends with "\"..?

Some users by mistake can type a directory like "C:\Users\Boris\Desktop" which will result in logs called "Desktop-yuniqlXXYYX" in the "\Users\Boris\" folder.

You can assign the ticket to me too.

**Comment by rdagumampan** [comment]
@bobi591, I realized this is actually bit complicated... The responsibility of checking if directory existing is delegated to `DirectoryService` and we can inject `IDirectoryService` into `FileTraceService` and check the existing of the explicit directory path for log file. If the directory doesnt exists, lets fall back into the current implementation which defaults to `Environment.CurrentDirectory` but log a Warning that directory doesnt exist and the log is placed in the same directory as the current diretory.

There are two places where the `FileTraceService` is created:
1. `Yuniql.CLI.Program`
2. `Yuniql.CLI.MigrationServiceFactory`

**Comment by rdagumampan** [comment]
> Also do you think it is a good idea to add another check in the same method that checks the if the Trace Directory string ends with \ ..?
> 
> Some users by mistake can type a directory like "C:\Users\Boris\Desktop" which will result in logs called "Desktop-yuniqlXXYYX" in the "\Users\Boris" folder.
> 

Agree, sounds perfect and I think if you use `Path.Combine` this is already handled but better to make tests to cover this scenario.
