### ISSUE TITLE
Providing table name for the schema version table cause error

### ISSUE THREAD

**Issue by gsrnadeem** [rdagumampan/yuniql#202]
Running yuniql run --debug  --platform postgresql --transaction-mode version --meta-schema public --meta-table DBVersion second time would cause error as the run is still checking for table __yuniqldbversion

![image](https://user-images.githubusercontent.com/60896880/113953861-9511e580-97cd-11eb-99d5-86c430b44439.png)

**Comment by rdagumampan** [comment]
@gsrnadeem , it seems to be bug and I have no tests that covered this so far. 
Thank you for reporting this issue and I hope you manage to find a work around. 

You may use the default tracking table name while I work on the patch to fix this issue.

Br, Rodel

**Comment by gsrnadeem** [comment]
Thank you @rdagumampan for you reply, I love the work you have done so far, it is a great tool, simple and powerful with many great features, and I'm looking deeply into the tool, so no work around for now, but I'm using the default name.

**Comment by rdagumampan** [comment]
Hi @gsrnadeem, I had more time to dig deeper into your case and I found this is issues is caused by the Pascal casing in your customer meta table name. Pgsql automatimatically fold down to lower case the object names when not enclosed in double qoutes. This means the first run, created `dbversion` table and not `DbVersion`. In the next run, yuniql will not be able to find `DbVersion` so it assumes the table does not exists but its just because its lower cased `dbversion`. If you used small case in your subsequent run, it will work just fine.

First run
```
yuniql run --debug --platform postgresql --transaction-mode version --meta-schema public --meta-table DBVersion
``` 

Subsequent runs
```
yuniql run --debug --platform postgresql --transaction-mode version --meta-schema public --meta-table dbversion
```
