### ISSUE TITLE
MySql transaction issues on failing of script

### ISSUE THREAD

**Issue by mguoth** [rdagumampan/yuniql#74]
Hello,
I am facing issues with MySql platform. The tool is designed that all Db scripts are executed in a single transaction. In case one of the script will fail, the tool will do rollback. Problem is that DDL scripts in MySql will causes implicit COMMIT (such behavior has also Oracle). Such transaction rollback is then not reliable, because it was partially committed by previously executed DDL scripts. Any idea how can I get over it? A possible workaround would be to construct new version scripts in a way that all DDL scripts need to run before all DML scripts (what can be limiting in use cases where it is not required). Any other ideas? Thx.

**Comment by rdagumampan** [comment]
Hi @mguoth , thanks for reaching out. 

You are right on this. The current version of yuniql doesn't support Transactional DDL operations in MySql. I also couldn't find evidence that it works in later version with InnoDB though MySql claims this is supported in v8.0+. I guess at statement level only but not within START/COMMIT TRANSACTION context. It has caught me by surprise when my transaction tests failed on MySql due to this.

I have no active work around on this right now and decided to state this is a known limitation when choosing MySql platform. 

You're idea I think would work in most cases. Alim's suggestion here seems to be best so far I've seen https://stackoverflow.com/questions/28197013/transactional-ddl-workflow-for-mysql

**Comment by mguoth** [comment]
I created 3 PR's, which enables yuniql to use the flow mentioned in stackoverflow thread above (without automatic reverse scripts for now). The idea is to deploy new DB version in multiple stages, where the each stage represents the yuniql version itself.

Example of such version scripts structure (the version directories can be named differently, there is also possibility to remove the not needed stage or to add the extra one):
[v0.00-Stage1.InitDDL]
      scripts causing implicit commit (e.g DDL)
[v0.00-Stage2.DML]
   [_transaction]
      scripts not causing implicit commit (e.g. DML)
[v0.00-Stage3.CleanupDDL]
      scripts causing implicit commit (e.g DDL)

The new version structure need to be created manually (The "vnext" doesn't support it for now).
